### ISSUE TITLE
Revit Version Problem

### ISSUE THREAD

**Issue by JD-Howard** [morbius1st/CreateSheets#1]
Hi Jeff,
I was being nosy, saw you did Revit work and noticed a bunch of version specific stuff going on. You might have specific reasons for that, but thought maybe the way I configure mine to operate out of a single code base could be useful.
https://gist.github.com/JD-Howard/4581b333e36a148b773370991d60e772

**Comment by morbius1st** [comment]
Thanks for the info.  Actually, in a general way, this is a "single code base".  That is, all of the projects labeled as shared are "shared projects" and are used by each of the year specific projects so their is only one copy / version of that code.  The year specific project just hold those files that are year specific (or were too much difficulty to break out).  I find it easier to keep each year and its associated files and settings independent.  This is especially important as each project references the year specific Revit DLL files.  This encapsulation helps prevent conflicts and multiple references.

**Comment by JD-Howard** [comment]
> This is especially important as each project references the year specific Revit DLL files. This encapsulation helps prevent conflicts and multiple references.

Well, what I attached does that too, but from a single sln file. You can switch from 2019 to 2021 just by selecting the 2021 debug configuration. Swaps out where its building/installing your dll's and all your external references to be 2021 versions.

Edit: I even have a placeholder in there for 2022. So, when it comes out, that is already setup too!

**Comment by morbius1st** [comment]
Cool.  I too have a single sln file.  I just have multiple projects.  I don't need to switch between them per se.  I can can work on all of them at the same time.  I only need to change the startup project to determine which builds and which version of Revit work on and debug.  2022 is in the works also.  But I really need to submit my 2021 version - I've been very lazy about that...

**Comment by JD-Howard** [comment]
Well, if you want to dig through that, it could definitively make your setup cleaner. Its fairly simplistic, it just defines configurations based on the year and then uses the $(Configuration) environment variable everywhere a 20XX reference appears to dynamically inject the correct context.

>  I really need to submit my 2021 version - I've been very lazy about that...

Yeah I know how that goes. The longer I work with a chunk of code, the less shinny and entertaining it gets.
